"""Query set for the DDIA rerank eval.

Authored from randomly sampled blocks, one natural question per block, BEFORE
any retrieval was run -- so the set cannot have been shaped by what the
bi-encoder happens to find. Questions deliberately paraphrase rather than quote,
so this tests semantic retrieval rather than keyword overlap.

Each entry is (candidate index, question). Ground truth is the sampled block.
"""
QUERIES = [
 (0,  "why can having two communication channels between services cause a race condition"),
 (1,  "why is recording what the user did better than recording which table rows changed"),
 (2,  "how does a stream processor recover its aggregation state after a crash"),
 (3,  "is there an isolation level that gives full serializability without the usual performance hit"),
 (6,  "why does storing a profile as one document avoid multi-way joins"),
 (7,  "how do supercomputers handle a failed node compared to cloud systems"),
 (8,  "what is meant by unbundling the database into separate components"),
 (9,  "why can you dump raw data into Hadoop but not into an MPP warehouse"),
 (10, "why is MapReduce built to survive tasks being killed part way through"),
 (11, "what happens when two doctors both take themselves off call at the same time"),
 (12, "why are transactions that span multiple partitions so much slower"),
 (13, "when is it pointless or dangerous to retry a failed transaction"),
 (14, "what is the difference between latency and response time"),
 (15, "how does a client know which node holds the partition it needs"),
 (17, "why does a simple append-only key value file need you to read the last occurrence"),
 (18, "why did people build higher level languages on top of MapReduce"),
 (19, "which fault tolerant consensus algorithms are the best known ones"),
 (20, "how is a distributed filesystem different from network attached storage"),
 (21, "how does searching a stream invert the usual relationship between queries and documents"),
 (22, "how do column stores handle inserts if the columns are compressed and sorted"),
 (23, "what goes wrong when the same user reads from a phone after writing on a laptop"),
 (24, "what does it mean for a node to lie in a distributed system"),
 (25, "why can a distributed filesystem store any kind of data while a database cannot"),
 (26, "how does hashing the key spread writes evenly across partitions"),
 (27, "why do a leader and a follower give different answers to the same query"),
 (28, "can you apologise to a user instead of strictly enforcing a uniqueness constraint"),
 (29, "why do you need a consistent snapshot before applying a change log"),
 (30, "how can database triggers be used to replicate data to another system"),
 (31, "what motivated people to move away from relational databases"),
 (32, "how do you describe the current load on a system before asking about growth"),
 (33, "why is it called two phase locking and what causes deadlock"),
 (34, "how long should a timeout be before declaring a node dead"),
 (35, "why must the lock used to elect a leader be linearizable"),
 (36, "how is causal consistency weaker than linearizability"),
 (37, "why is a declarative style better than manually looping over page elements"),
 (38, "why do applications need both a database and a separate search index"),
 (39, "what is a logical replication log and how does it differ from the storage format"),
 (40, "who proposed the relational model and how long has it dominated"),
 (41, "how are partition boundaries picked when a new node joins the cluster"),
 (42, "which replication methods can be made linearizable"),
 (43, "why is it wrong to claim most people only need one kind of data system"),
 (44, "which companies created Thrift and Protocol Buffers and what do they require"),
 (45, "why is an event log by itself not very useful to users"),
 (46, "how many columns do fact and dimension tables typically have"),
 (48, "two clients increment a counter and it only goes up by one, why"),
 (49, "why are declarative languages easier to run in parallel across many cores"),
 (50, "why does one slow backend call make the whole user request slow"),
 (51, "how do you make a join deterministic when the tax rate changes over time"),
 (52, "how are bitmap indexes used to answer a query with IN or AND"),
 (54, "what does atomicity promise if a write fails half way through"),
 (55, "can cryptographic tools prove the integrity of a database"),
 (56, "why is pick two out of three a misleading way to describe CAP"),
 (57, "why can't you update a compressed column in place"),
 (58, "why does MapReduce read all the input files instead of using an index"),
 (59, "how do you guard against corrupted packets without full Byzantine fault tolerance"),
 (60, "why can a write that happened later end up with an earlier timestamp"),
 (61, "why is syncing a calendar across your devices like multi leader replication"),
 (62, "why can't users give meaningful consent about how their data is used"),
 (63, "why does partitioning by timestamp overload a single partition"),
 (64, "what makes Avro different from Protocol Buffers and Thrift"),
 (65, "why is collected data sometimes described as hazardous material"),
 (66, "what is the difference between the two kinds of clocks a computer has"),
 (67, "how does a client side javascript application act as an HTTP client"),
 (68, "which is faster for writes, LSM trees or B trees, and why are reads slower"),
 (69, "what is the precise difference between a safety property and a liveness property"),
 (70, "how do textual and binary schema driven formats compare for compatibility"),
 (71, "how would you store vertices and edges in a relational schema"),
 (72, "how does Avro handle the writer and the reader having different schemas"),
 (73, "what does a message broker do for producers and consumers that come and go"),
 (74, "why is querying a remote database for every single event too slow"),
 (75, "why do different databases use different names for snapshot isolation"),
 (76, "what rules let you read your own profile from the leader but others from a follower"),
 (78, "why would you write read requests to durable storage"),
 (79, "where else in this book does the ordering of operations come up"),
 (80, "how is realtime collaborative document editing related to replication"),
 (81, "why do you only need backward compatibility on requests in an RPC scheme"),
 (82, "why are more applications now designed to tolerate whole machines failing"),
 (83, "why is TCP not enough to guarantee application level correctness"),
 (84, "even when w plus r is greater than n why can you still read stale values"),
 (85, "how do layers of data models hide complexity from each other"),
 (86, "what is XA and which databases and message brokers support it"),
 (87, "what is a star schema in a data warehouse"),
 (88, "how many MapReduce jobs are typical in a recommendation system workflow"),
 (89, "how can you transfer money correctly without an atomic commit protocol"),
 (90, "which schedulers handle dependencies between Hadoop job executions"),
 (91, "can a system give strong integrity guarantees without any coordination"),
 (92, "what does the 99.9th percentile response time mean and why does Amazon care"),
 (93, "how does an event log keep a system robust when one consumer fails"),
 (94, "what problem do very large integers cause in JSON"),
 (95, "how does a distributed filesystem tolerate a disk or a machine failing"),
 (97, "why must every column file contain the rows in the same order"),
 (98, "what is wrong with code that renews a lease based on the system clock"),
 (99, "what does it mean to materialize a conflict and why is it a last resort"),
 (101, "why does an application end up with the same data in several different systems"),
 (104, "why must the quorum for leader election overlap with the quorum for a proposal"),
 (105, "which matters more in practice, integrity or timeliness, and why"),
 (106, "how can the write ahead log be reused to build a replica on another node"),
 (107, "what are forward and backward compatibility and why do they matter for evolvability"),
 (108, "what kinds of decisions in a distributed system require consensus"),
 (109, "what is the danger of declaring a node dead too early"),
]
